export const POINT_FETCH_START = 'POINT_FETCH_START';
export const POINT_FETCH_END = 'POINT_FETCH_END';
export const POINT_CLEAR_LIST = 'POINT_CLEAR_LIST';
export const POINT_ADD_POINT = 'POINT_ADD_POINT';
export const POINT_CREATE_POINT = 'POINT_CREATE_POINT';
export const POINT_DELETE_POINT = 'POINT_DELETE_POINT';
export const POINT_UPDATE_POINT = 'POINT_UPDATE_POINT';
