export const CLIENT_FETCH_START = 'CLIENT_FETCH_START';
export const CLIENT_FETCH_END = 'CLIENT_FETCH_END';
export const CLIENT_CLEAR_LIST = 'CLIENT_CLEAR_LIST';
export const CLIENT_ADD_CLIENT = 'CLIENT_ADD_CLIENT';
