export const ORDER_CREATE_ORDER = 'ORDER_CREATE_ORDER';
export const ORDER_FETCH_START = 'ORDER_FETCH_START';
export const ORDER_FETCH_END = 'ORDER_FETCH_END';
export const ORDER_CLEAR_LIST = 'ORDER_CLEAR_LIST';
export const ORDER_ADD_ORDER = 'ORDER_ADD_ORDER';
export const ORDER_UPDATE_ORDER = 'ORDER_UPDATE_ORDER';
