export const PROFILE_FETCH_START = 'PROFILE_FETCH_START';
export const PROFILE_FETCH_END = 'PROFILE_FETCH_END';
export const PROFILE_SET_USER = 'PROFILE_SET_USER';
export const PROFILE_REMOVE_USER = 'PROFILE_REMOVE_USER';
